apiVersion: v1
kind: Service
metadata:
  name: secure-api
  namespace: security-demo
spec:
  type: ClusterIP
  selector:
    app: secure-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
